"""empty message

Revision ID: 28b8b01084cd
Revises: 0fb9217ca6e4
Create Date: 2023-03-21 18:57:13.551138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b8b01084cd'
down_revision = '0fb9217ca6e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('imageUrl', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('imageUrl')
        batch_op.drop_column('description')

    # ### end Alembic commands ###