"""empty message

Revision ID: fd1452fcf3f8
Revises: 28b8b01084cd
Create Date: 2023-03-24 16:37:04.240006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd1452fcf3f8'
down_revision = '28b8b01084cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('review',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reviews')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('review',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###